###############################################################################
#                          API                                                #
###############################################################################
version: '3.8'
services:
    
    memcached:
        container_name: memcached-api
        image: 'memcached:alpine'

    redis:
        container_name: redis-api
        image: 'redis:alpine'

    database:
        container_name: database-api
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"

    php-fpm:
        depends_on:
            - database
        container_name: phpserver-api
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        command: bash -c 'composer install && php bin/console doctrine:database:create && php-fpm8.2 -F'

    webserver:
        depends_on:
            - php-fpm
        container_name: webserver-api
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'